__default__:
  account: sansam-lab
  partition: serial
  time: "08:00:00"
  cpus-per-task: 2
  mem: "16G"
  name: "{rule}.{wildcards}"
  output: "logs/snakefiles/{rule}.%j.out"
  error:  "logs/snakefiles/{rule}.%j.err"

# STAR build index (usually once)
index:
  cpus-per-task: 24
  mem: "64G"
  time: "08:00:00"
  name: "{rule}"

# STAR align (per sample)
align:
  cpus-per-task: 24
  mem: "64G"
  time: "08:00:00"
  name: "{rule}.{wildcards.sample}"

# sort/filter BAM (per sample)
sort_filter:
  cpus-per-task: 8
  mem: "32G"
  time: "04:00:00"
  name: "{rule}.{wildcards.sample}"

# mutation counting (per sample) — often heavy
cnt_muts:
  cpus-per-task: 32
  mem: "96G"
  time: "12:00:00"
  name: "{rule}.{wildcards.sample}"

# duckdb merge (per sample) — heavy
merge_features_and_muts:
  cpus-per-task: 32
  mem: "96G"
  time: "12:00:00"
  name: "{rule}.{wildcards.sample}"

# featureCounts (per sample)
featurecounts_genes:
  cpus-per-task: 20
  mem: "32G"
  time: "04:00:00"
  name: "{rule}.{wildcards.sample}"

featurecounts_exons:
  cpus-per-task: 20
  mem: "32G"
  time: "04:00:00"
  name: "{rule}.{wildcards.sample}"

# RSEM (per sample)
RSEM:
  cpus-per-task: 20
  mem: "64G"
  time: "08:00:00"
  name: "{rule}.{wildcards.sample}"

# MultiQC (once)
multiqc:
  cpus-per-task: 2
  mem: "8G"
  time: "01:00:00"
  name: "{rule}"
